[package]
name = "legal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = { version = "0.27.0", features = ["token"] }
solana-program = "1.17.19"

[features]
default = []
